name = "SortingAlgorithms"
uuid = "e1665874-7b75-4812-a52a-f2ab1bbdc19b"
authors = ["kylebrown <kylejbrown17@gmail.com>"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
